// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/chunkService.proto

package chunkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	SeqNo         int32                  `protobuf:"varint,3,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	Checksum      uint32                 `protobuf:"varint,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_proto_chunkService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chunkService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_proto_chunkService_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkData) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChunkData) GetSeqNo() int32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *ChunkData) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

type DownloadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunkRequest) Reset() {
	*x = DownloadChunkRequest{}
	mi := &file_proto_chunkService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunkRequest) ProtoMessage() {}

func (x *DownloadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chunkService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunkRequest.ProtoReflect.Descriptor instead.
func (*DownloadChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_chunkService_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type UploadChunkStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkStatus) Reset() {
	*x = UploadChunkStatus{}
	mi := &file_proto_chunkService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkStatus) ProtoMessage() {}

func (x *UploadChunkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chunkService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkStatus.ProtoReflect.Descriptor instead.
func (*UploadChunkStatus) Descriptor() ([]byte, []int) {
	return file_proto_chunkService_proto_rawDescGZIP(), []int{2}
}

func (x *UploadChunkStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_chunkService_proto protoreflect.FileDescriptor

const file_proto_chunkService_proto_rawDesc = "" +
	"\n" +
	"\x18proto/chunkService.proto\x12\x05chunk\"m\n" +
	"\tChunkData\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x15\n" +
	"\x06seq_no\x18\x03 \x01(\x05R\x05seqNo\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\rR\bchecksum\"1\n" +
	"\x14DownloadChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"-\n" +
	"\x11UploadChunkStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8d\x01\n" +
	"\fChunkService\x12;\n" +
	"\vUploadChunk\x12\x10.chunk.ChunkData\x1a\x18.chunk.UploadChunkStatus(\x01\x12@\n" +
	"\rDownloadChunk\x12\x1b.chunk.DownloadChunkRequest\x1a\x10.chunk.ChunkData0\x01B\rZ\vdfs/chunkpbb\x06proto3"

var (
	file_proto_chunkService_proto_rawDescOnce sync.Once
	file_proto_chunkService_proto_rawDescData []byte
)

func file_proto_chunkService_proto_rawDescGZIP() []byte {
	file_proto_chunkService_proto_rawDescOnce.Do(func() {
		file_proto_chunkService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chunkService_proto_rawDesc), len(file_proto_chunkService_proto_rawDesc)))
	})
	return file_proto_chunkService_proto_rawDescData
}

var file_proto_chunkService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_chunkService_proto_goTypes = []any{
	(*ChunkData)(nil),            // 0: chunk.ChunkData
	(*DownloadChunkRequest)(nil), // 1: chunk.DownloadChunkRequest
	(*UploadChunkStatus)(nil),    // 2: chunk.UploadChunkStatus
}
var file_proto_chunkService_proto_depIdxs = []int32{
	0, // 0: chunk.ChunkService.UploadChunk:input_type -> chunk.ChunkData
	1, // 1: chunk.ChunkService.DownloadChunk:input_type -> chunk.DownloadChunkRequest
	2, // 2: chunk.ChunkService.UploadChunk:output_type -> chunk.UploadChunkStatus
	0, // 3: chunk.ChunkService.DownloadChunk:output_type -> chunk.ChunkData
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_chunkService_proto_init() }
func file_proto_chunkService_proto_init() {
	if File_proto_chunkService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chunkService_proto_rawDesc), len(file_proto_chunkService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chunkService_proto_goTypes,
		DependencyIndexes: file_proto_chunkService_proto_depIdxs,
		MessageInfos:      file_proto_chunkService_proto_msgTypes,
	}.Build()
	File_proto_chunkService_proto = out.File
	file_proto_chunkService_proto_goTypes = nil
	file_proto_chunkService_proto_depIdxs = nil
}
