// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/masterService.proto

package masterpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterChunkServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerAddress string                 `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	FreeStorage   int64                  `protobuf:"varint,2,opt,name=free_storage,json=freeStorage,proto3" json:"free_storage,omitempty"`
	Chunks        []string               `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChunkServerRequest) Reset() {
	*x = RegisterChunkServerRequest{}
	mi := &file_proto_masterService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChunkServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChunkServerRequest) ProtoMessage() {}

func (x *RegisterChunkServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChunkServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterChunkServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterChunkServerRequest) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *RegisterChunkServerRequest) GetFreeStorage() int64 {
	if x != nil {
		return x.FreeStorage
	}
	return 0
}

func (x *RegisterChunkServerRequest) GetChunks() []string {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type RegisterChunkServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChunkServerResponse) Reset() {
	*x = RegisterChunkServerResponse{}
	mi := &file_proto_masterService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChunkServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChunkServerResponse) ProtoMessage() {}

func (x *RegisterChunkServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChunkServerResponse.ProtoReflect.Descriptor instead.
func (*RegisterChunkServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterChunkServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerAddress string                 `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	FreeStorage   int64                  `protobuf:"varint,2,opt,name=free_storage,json=freeStorage,proto3" json:"free_storage,omitempty"`
	Chunks        []string               `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"` // stores chunk IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_masterService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *HeartbeatRequest) GetFreeStorage() int64 {
	if x != nil {
		return x.FreeStorage
	}
	return 0
}

func (x *HeartbeatRequest) GetChunks() []string {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type HeartbeatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReplicationTasks []*ReplicationTask     `protobuf:"bytes,1,rep,name=replication_tasks,json=replicationTasks,proto3" json:"replication_tasks,omitempty"`
	DeleteTasks      []*DeleteTask          `protobuf:"bytes,2,rep,name=delete_tasks,json=deleteTasks,proto3" json:"delete_tasks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_masterService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetReplicationTasks() []*ReplicationTask {
	if x != nil {
		return x.ReplicationTasks
	}
	return nil
}

func (x *HeartbeatResponse) GetDeleteTasks() []*DeleteTask {
	if x != nil {
		return x.DeleteTasks
	}
	return nil
}

type ReplicationTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	TargetAddress string                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationTask) Reset() {
	*x = ReplicationTask{}
	mi := &file_proto_masterService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationTask) ProtoMessage() {}

func (x *ReplicationTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationTask.ProtoReflect.Descriptor instead.
func (*ReplicationTask) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicationTask) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ReplicationTask) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

type DeleteTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTask) Reset() {
	*x = DeleteTask{}
	mi := &file_proto_masterService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTask) ProtoMessage() {}

func (x *DeleteTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTask.ProtoReflect.Descriptor instead.
func (*DeleteTask) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTask) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type AllocateChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunkRequest) Reset() {
	*x = AllocateChunkRequest{}
	mi := &file_proto_masterService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkRequest) ProtoMessage() {}

func (x *AllocateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkRequest.ProtoReflect.Descriptor instead.
func (*AllocateChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{6}
}

func (x *AllocateChunkRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AllocateChunkRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type AllocateChunkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunkId        string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	ReplicaServers []string               `protobuf:"bytes,2,rep,name=replica_servers,json=replicaServers,proto3" json:"replica_servers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AllocateChunkResponse) Reset() {
	*x = AllocateChunkResponse{}
	mi := &file_proto_masterService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunkResponse) ProtoMessage() {}

func (x *AllocateChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunkResponse.ProtoReflect.Descriptor instead.
func (*AllocateChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{7}
}

func (x *AllocateChunkResponse) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *AllocateChunkResponse) GetReplicaServers() []string {
	if x != nil {
		return x.ReplicaServers
	}
	return nil
}

type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_proto_masterService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileInfoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetFileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileInfo      []*FileChunkInfo       `protobuf:"bytes,1,rep,name=file_info,json=fileInfo,proto3" json:"file_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoResponse) Reset() {
	*x = GetFileInfoResponse{}
	mi := &file_proto_masterService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResponse) ProtoMessage() {}

func (x *GetFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{9}
}

func (x *GetFileInfoResponse) GetFileInfo() []*FileChunkInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

type FileChunkInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunkId        string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	ReplicaServers []string               `protobuf:"bytes,2,rep,name=replica_servers,json=replicaServers,proto3" json:"replica_servers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileChunkInfo) Reset() {
	*x = FileChunkInfo{}
	mi := &file_proto_masterService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunkInfo) ProtoMessage() {}

func (x *FileChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunkInfo.ProtoReflect.Descriptor instead.
func (*FileChunkInfo) Descriptor() ([]byte, []int) {
	return file_proto_masterService_proto_rawDescGZIP(), []int{10}
}

func (x *FileChunkInfo) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *FileChunkInfo) GetReplicaServers() []string {
	if x != nil {
		return x.ReplicaServers
	}
	return nil
}

var File_proto_masterService_proto protoreflect.FileDescriptor

const file_proto_masterService_proto_rawDesc = "" +
	"\n" +
	"\x19proto/masterService.proto\x12\x06master\"~\n" +
	"\x1aRegisterChunkServerRequest\x12%\n" +
	"\x0eserver_address\x18\x01 \x01(\tR\rserverAddress\x12!\n" +
	"\ffree_storage\x18\x02 \x01(\x03R\vfreeStorage\x12\x16\n" +
	"\x06chunks\x18\x03 \x03(\tR\x06chunks\"7\n" +
	"\x1bRegisterChunkServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"t\n" +
	"\x10HeartbeatRequest\x12%\n" +
	"\x0eserver_address\x18\x01 \x01(\tR\rserverAddress\x12!\n" +
	"\ffree_storage\x18\x02 \x01(\x03R\vfreeStorage\x12\x16\n" +
	"\x06chunks\x18\x03 \x03(\tR\x06chunks\"\x90\x01\n" +
	"\x11HeartbeatResponse\x12D\n" +
	"\x11replication_tasks\x18\x01 \x03(\v2\x17.master.ReplicationTaskR\x10replicationTasks\x125\n" +
	"\fdelete_tasks\x18\x02 \x03(\v2\x12.master.DeleteTaskR\vdeleteTasks\"S\n" +
	"\x0fReplicationTask\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\tR\rtargetAddress\"'\n" +
	"\n" +
	"DeleteTask\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"T\n" +
	"\x14AllocateChunkRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\"[\n" +
	"\x15AllocateChunkResponse\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12'\n" +
	"\x0freplica_servers\x18\x02 \x03(\tR\x0ereplicaServers\"1\n" +
	"\x12GetFileInfoRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"I\n" +
	"\x13GetFileInfoResponse\x122\n" +
	"\tfile_info\x18\x01 \x03(\v2\x15.master.FileChunkInfoR\bfileInfo\"S\n" +
	"\rFileChunkInfo\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12'\n" +
	"\x0freplica_servers\x18\x02 \x03(\tR\x0ereplicaServers2\xcb\x02\n" +
	"\rMasterService\x12F\n" +
	"\vGetFileInfo\x12\x1a.master.GetFileInfoRequest\x1a\x1b.master.GetFileInfoResponse\x12L\n" +
	"\rAllocateChunk\x12\x1c.master.AllocateChunkRequest\x1a\x1d.master.AllocateChunkResponse\x12^\n" +
	"\x13RegisterChunkServer\x12\".master.RegisterChunkServerRequest\x1a#.master.RegisterChunkServerResponse\x12D\n" +
	"\tHeartbeat\x12\x18.master.HeartbeatRequest\x1a\x19.master.HeartbeatResponse(\x010\x01B\x0eZ\fdfs/masterpbb\x06proto3"

var (
	file_proto_masterService_proto_rawDescOnce sync.Once
	file_proto_masterService_proto_rawDescData []byte
)

func file_proto_masterService_proto_rawDescGZIP() []byte {
	file_proto_masterService_proto_rawDescOnce.Do(func() {
		file_proto_masterService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_masterService_proto_rawDesc), len(file_proto_masterService_proto_rawDesc)))
	})
	return file_proto_masterService_proto_rawDescData
}

var file_proto_masterService_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_masterService_proto_goTypes = []any{
	(*RegisterChunkServerRequest)(nil),  // 0: master.RegisterChunkServerRequest
	(*RegisterChunkServerResponse)(nil), // 1: master.RegisterChunkServerResponse
	(*HeartbeatRequest)(nil),            // 2: master.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 3: master.HeartbeatResponse
	(*ReplicationTask)(nil),             // 4: master.ReplicationTask
	(*DeleteTask)(nil),                  // 5: master.DeleteTask
	(*AllocateChunkRequest)(nil),        // 6: master.AllocateChunkRequest
	(*AllocateChunkResponse)(nil),       // 7: master.AllocateChunkResponse
	(*GetFileInfoRequest)(nil),          // 8: master.GetFileInfoRequest
	(*GetFileInfoResponse)(nil),         // 9: master.GetFileInfoResponse
	(*FileChunkInfo)(nil),               // 10: master.FileChunkInfo
}
var file_proto_masterService_proto_depIdxs = []int32{
	4,  // 0: master.HeartbeatResponse.replication_tasks:type_name -> master.ReplicationTask
	5,  // 1: master.HeartbeatResponse.delete_tasks:type_name -> master.DeleteTask
	10, // 2: master.GetFileInfoResponse.file_info:type_name -> master.FileChunkInfo
	8,  // 3: master.MasterService.GetFileInfo:input_type -> master.GetFileInfoRequest
	6,  // 4: master.MasterService.AllocateChunk:input_type -> master.AllocateChunkRequest
	0,  // 5: master.MasterService.RegisterChunkServer:input_type -> master.RegisterChunkServerRequest
	2,  // 6: master.MasterService.Heartbeat:input_type -> master.HeartbeatRequest
	9,  // 7: master.MasterService.GetFileInfo:output_type -> master.GetFileInfoResponse
	7,  // 8: master.MasterService.AllocateChunk:output_type -> master.AllocateChunkResponse
	1,  // 9: master.MasterService.RegisterChunkServer:output_type -> master.RegisterChunkServerResponse
	3,  // 10: master.MasterService.Heartbeat:output_type -> master.HeartbeatResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_masterService_proto_init() }
func file_proto_masterService_proto_init() {
	if File_proto_masterService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_masterService_proto_rawDesc), len(file_proto_masterService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_masterService_proto_goTypes,
		DependencyIndexes: file_proto_masterService_proto_depIdxs,
		MessageInfos:      file_proto_masterService_proto_msgTypes,
	}.Build()
	File_proto_masterService_proto = out.File
	file_proto_masterService_proto_goTypes = nil
	file_proto_masterService_proto_depIdxs = nil
}
